youtube_analytics:
  target: prod
  outputs:
    prod:
      type: bigquery
      method: service-account
      project: orbital-nuance-471817-n0
      dataset: youtube_stg
      location: US
      threads: 4
      keyfile: "D:\\UC Davis Documents & Works\\Interview Preparation\\self_projects\\youtube-analytics-pipeline\\creds\\gcp_sa.json"